export const GET_PROJECTS = "GET_PROJECTS";
export const POST_PROJECT = "POST_PROJECT";
export const PUT_PROJECT = "PUT_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const PROJECTS_ERROR = "PROJECTS_ERROR";

export const SELECT_PROJECT = "SELECT_PROJECT";
export const REMOVE_PROJECT = "REMOVE_PROJECT";
